### ISSUE TITLE
Copy paste keyboard support

### ISSUE THREAD

**Issue by nicolechung** [CrowdStrike/ember-aria#27]
As a user of `{{aria-grid}}` it would also be nice if there was keyboard support for copy and pasting, so that power users could get more done.

**Comment by NullVoxPopuli** [comment]
Why should this be the responsibility of aria-grid?

There is this https://support.google.com/chrome/answer/10129654?hl=en
which works pretty well by keeping the cursor synced with tab/focus

**Comment by nicolechung** [comment]
Going to close this as seems like it's a browser supported thing.
